import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import SessionProvider from "../app/components/sessionProvider"
const inter = Inter({ subsets: ["latin"] });
import { getServerSession } from "next-auth";
import { NavBar } from "./components/navBar";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session=await getServerSession()
  return (
    <html lang="en">
      <body className={inter.className}>
        <SessionProvider session={session}>
          <NavBar/>

        {children}
        </SessionProvider>
        </body>

    </html>
  );
}
